export const employeeData = [
  { id: 1, name: "John Doe", department: "IT", salary: 50000 },
  { id: 2, name: "Jane Smith", department: "HR", salary: 45000 },
  { id: 3, name: "Michael Johnson", department: "Finance", salary: 60000 },
  { id: 4, name: "Emily Brown", department: "Marketing", salary: 55000 },
  { id: 5, name: "David Lee", department: "Sales", salary: 65000 },
  { id: 6, name: "Sarah Kim", department: "Operations", salary: 48000 },
  { id: 7, name: "Robert Taylor", department: "IT", salary: 52000 },
  { id: 8, name: "Olivia Wilson", department: "HR", salary: 47000 },
  { id: 9, name: "William Clark", department: "Finance", salary: 58000 },
  { id: 10, name: "Sophia Anderson", department: "Marketing", salary: 53000 },
  { id: 11, name: "Ethan Davis", department: "Sales", salary: 62000 },
  { id: 12, name: "Ava Miller", department: "Operations", salary: 49000 },
  { id: 13, name: "Noah Thomas", department: "IT", salary: 51000 },
  { id: 14, name: "Ella Harris", department: "HR", salary: 46000 },
  { id: 15, name: "Jacob Martin", department: "Finance", salary: 59000 },
  { id: 16, name: "Mia Campbell", department: "Marketing", salary: 54000 },
  { id: 17, name: "Logan Wilson", department: "Sales", salary: 63000 },
  { id: 18, name: "Avery Rogers", department: "Operations", salary: 50000 },
  { id: 19, name: "Henry Adams", department: "IT", salary: 55000 },
  { id: 20, name: "Charlotte Carter", department: "HR", salary: 49000 },
];
